# This file speeds up the linking phase on Windows if LLD is installed.
[build]
target-dir = "target"

[target.x86_64-pc-windows-msvc]
linker = "C:\\Program Files\\LLVM\\bin\\lld-link.exe"
# rustflags = ["-Zshare-generics=y"] # Removed as it requires Nightly
